name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_SEPHORA_BOT }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('./yarn.lock') }}
      - bundle install
      - rake db:create RAILS_ENV=test
      - rake db:migrate RAILS_ENV=test
      - bundle exec rspec
